/**
 * MediaEntry model.
 *
 * Mirrors the `mediaEntries` table fields exactly as defined in the
 * Database Schema & Data Model document, section 3.
 */

/** A single metadata field value. Kept loosely typed because metadata
 * shape is defined per `MediaType.fields`, not hard-coded per type
 * (see models/MediaType.ts). Per-type validation rules live in
 * services/validation/entrySchemas.ts. */
export type MetadataValue = string | number | boolean | undefined;

export type EntryMetadata = Record<string, MetadataValue>;

export interface MediaEntry {
  id: string;
  title: string;
  /** References `MediaType.id`. */
  mediaType: string;
  /** ISO date string (yyyy-mm-dd). Optional. */
  startedDate?: string;
  /** ISO date string (yyyy-mm-dd). Required; defaults to today on creation. */
  completedDate: string;
  /** 0–10 in 0.5 increments. Optional. */
  rating?: number;
  notes?: string;
  /** Re-read / re-watch flag. */
  repeatConsumption: boolean;
  /** Media-specific fields (author, director, season number, etc.). */
  metadata: EntryMetadata;
  /**
   * Calendar year of `completedDate`, stored redundantly so it can be
   * indexed — IndexedDB cannot index a value derived at query time.
   * Always kept in sync by entryService; nothing outside that service
   * should set it directly. See Database Schema & Data Model, section
   * 12 (Indexing Strategy) and section 8 (Derived Values).
   */
  completedYear: number;
  createdAt: string;
  updatedAt: string;
}

/** Fields supplied by the user when creating a new entry; the rest
 * (id, completedYear, createdAt, updatedAt) are generated by the
 * service layer. */
export type NewMediaEntryInput = Omit<
  MediaEntry,
  'id' | 'completedYear' | 'createdAt' | 'updatedAt'
>;

/** Fields that may be changed when editing an existing entry. */
export type MediaEntryUpdate = Partial<NewMediaEntryInput>;
